spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/user-service
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true
    default-schema: user-service
  security:
    user:
      name: irfan # default username
      password: "$2a$12$8bgKpthG2vU6nqFH4gYZge9IWJGunS6HDud8KvCeTeHloeKY7h6Fq" # BCrypt encoded password

server:
  port: 8081
